name: Update README with Top 3 Repositories by Commits

on:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC
  workflow_dispatch:  # Manually triggerable from GitHub UI

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js (for script execution)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Can be adjusted if needed

      - name: Install dependencies
        run: npm install axios

      - name: Get repositories and fetch commit counts
        id: get_repos
        run: |
          const axios = require('axios');
          const fs = require('fs');
          
          // GitHub API to fetch user repositories
          const username = 'ntrongphuc1302';  # Replace with your GitHub username
          const token = process.env.GITHUB_TOKEN;  # GitHub token for authentication
          
          // GitHub API URL to fetch all repositories
          const url = `https://api.github.com/users/${username}/repos?sort=updated&per_page=100`;

          async function fetchRepos() {
            try {
              const response = await axios.get(url, {
                headers: { Authorization: `token ${token}` }
              });
              const repos = response.data;

              // Fetch commit history for each repository
              let repoCommitData = [];

              for (let repo of repos) {
                const commitsUrl = `https://api.github.com/repos/${username}/${repo.name}/commits?per_page=1`;
                const commitsResponse = await axios.get(commitsUrl, {
                  headers: { Authorization: `token ${token}` }
                });
                const commitCount = commitsResponse.headers['x-total-count'];

                // Collect repo name, description, and commit count
                repoCommitData.push({
                  name: repo.name,
                  description: repo.description || 'No description available.',
                  commits: parseInt(commitCount)
                });
              }

              // Sort repos by commit count in descending order
              repoCommitData.sort((a, b) => b.commits - a.commits);

              // Get the top 3 repositories (or more if desired)
              const topRepos = repoCommitData.slice(0, 4);  # Change to 3 or 4 based on needs

              // Write the top repos data to a JSON file
              fs.writeFileSync('top-repos.json', JSON.stringify(topRepos, null, 2));
            } catch (error) {
              console.error('Error fetching repositories or commits:', error);
            }
          }

          fetchRepos();
        
      - name: Update README with the top repositories
        run: |
          const fs = require('fs');
          const topRepos = require('./top-repos.json');

          if (!topRepos || topRepos.length === 0) {
            console.error('No repositories found.');
            return;
          }

          const readmePath = './README.md';
          let readmeContent = fs.readFileSync(readmePath, 'utf8');

          // Construct the new "Top Repositories" section
          let topRepoSection = `
## Top Repositories by Commits

Here are the top repositories with the most commits:

`;

          topRepos.forEach((repo, index) => {
            topRepoSection += `
1. **[${repo.name}](https://github.com/ntrongphuc1302/${repo.name})**  
   - **Commits**: ${repo.commits}  
   - **Description**: ${repo.description}

`;
          });

          // Replace the old "Top Repositories" section with the updated one
          const updatedContent = readmeContent.replace(
            /## Top Repositories by Commits[\s\S]*?##/g,  # Match existing section
            topRepoSection
          );

          // If section doesn't exist, add it
          if (updatedContent === readmeContent) {
            readmeContent += topRepoSection;
          }

          // Write the updated content back to README.md
          fs.writeFileSync(readmePath, updatedContent, 'utf8');

      - name: Commit and push changes to README
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'GitHub Actions'
          author_email: 'github-actions@github.com'
          message: 'Update README with top repositories by commits'
